config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # to (コントローラー名)(実行するアクション)


  # ログイン画面
  get 'login', to: 'sessions#new'          # ログインフォームを表示
  post 'login', to: 'sessions#create'      # ログイン処理
  delete 'logout', to: 'sessions#destroy'  # ログアウト処理


  resources :users, only: [:show] do
    collection do
      get 'home', to: 'users#home', as: 'home'
    end

    resources :companies, only: [:show]

    resources :works, only: [:index, :show, :create, :update] do
      get 'get_timeline_data', on: :member  # タイムラインデータを取得するルート
    end
    resources :breaks, only: [:index, :show, :create, :update]
  end

  # 管理者専用の操作
  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :companies, only: [:edit, :update]
  end

  post 'reset_demo_data', to: 'application#reset_demo_data'

  # 管理者モードの切り替え
  post 'toggle_admin_mode', to: 'admin#toggle_admin_mode'

  # ルートページをログイン画面に設定
  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord

  # ===============
  # アソシエーション
  # ===============
  has_many :works, dependent: :destroy
  has_many :breaks, through: :works  # workを経由してbreaksを取得
  belongs_to :department, optional: true # nilを許容
  belongs_to :company

  # ===============
  # enum 定義
  # ===============
  enum working_status: {
    working: 0,       # 勤務している
    breaking: 1,      # 休憩中
    not_working: 2,   # 勤務していない
    retired: 3        # 退職している
  }

  # ===============
  # バリデーション
  # ===============
  has_secure_password # パスワードをハッシュ化
  # 必須項目のバリデーション
  validates:employee_number, :first_name, :family_name, :birthday, :date_of_hire, presence: true
  # 社員番号の一意性チェック
  validates :employee_number, uniqueness: true
  # 名前のバリデーション
  with_options length: { maximum: 20 }, format: { with: /\A[ぁ-んァ-ン一-龥a-zA-Z]/ } do
    validates :first_name
    validates :family_name
  end
  # 名前（かな）のバリデーション
  with_options allow_blank: true, length: { maximum: 30 }, format: { with: /\A[ぁ-ん]+\z/ } do
    validates :first_name_kana
    validates :family_name_kana
  end

  # ===============
  # スコープ
  # ===============

  # adminユーザー以外を取得
  # scope :non_admin, ->{ where(is_admin: false) } #NOTE 不要なら削除

  # 社員番号の小さい順に並び替え
  scope :ordered_by_employee_number, -> { order(:employee_number) }

  #退職済みユーザー(退職カラムが存在するかつ、退職日が過去)
  scope :retired, -> { where.not(date_of_termination: nil).where('date_of_termination < ?', Date.today) }

  #在職ユーザー(退職カラムが存在しないもしくは、退職カラムが存在かつ退職日が今日以降)
  scope :active, -> { where(date_of_termination: nil).or(where('date_of_termination >= ?', Date.today)) }

  # ===============
  # メソッド
  # ===============

  # 勤務中か判定
  def working?
    latest_work = works.order(created_at: :desc).first
    # 最新のレコードに出勤記録が存在する、かつ退勤記録が存在しない
    latest_work&.start_datetime.present? && latest_work&.end_datetime.nil?
  end

  # 休憩中か判定
  def taking_a_break?
    latest_break = breaks.order(created_at: :desc).first
    # 最新の休憩レコードに休憩開始記録が存在、かつ休憩終了記録が存在しない
    latest_break&.start_datetime.present? && latest_break&.end_datetime.nil?
  end


  # 新規ユーザーの社員番号を取得
  def self.next_employee_number
    latest_employee_number  = User.maximum(:employee_number).to_i
    latest_employee_number + 1
  end

  # working_statusを文字列に変換
  def working_status_str
    case working_status
    when "working"
      "勤務中"
    when "breaking"
      "休憩中"
    when "not_working"
      "勤務外"
    when "retired"
      "退職"
    else
      "未登録"
    end
  end

  # 在職か判定
  def active?
    date_of_termination.nil? || date_of_termination >= Date.today
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_admin_mode
  before_action -> { set_and_verify_user(:id) }, only:[ :edit, :update]

  # ユーザー一覧画面
  def index

    @sort_column = params[:sort_column] || 'employee_number' # デフォルトは社員番号
    @sort_direction = params[:sort_direction] || 'asc'      # デフォルトは昇順
    @filter = params[:filter] || 'active'                   # デフォルトは「在職」
    @department_id = params[:department_id].presence || ''   # 部署ID（フィルター）、初期値は空

    @users = User.all
    @users = filter_users(@users, @filter) # ステータスフィルターを適用

    # 部署IDが指定されている場合の絞り込み
    if @department_id.present?
      if @department_id == 'none'
        @users = @users.where(department_id: nil) # 未選択（NULL）の場合
      else
        @users = @users.where(department_id: @department_id) # 指定された部署IDの場合
      end
    end
    @department_label = department_filter_label(@department_id)
    @employee_label = employee_filter_label(@filter)

    # 並べ替え
    @users = @users.order("#{sort_column} #{sort_direction}, id ASC")
  end

  # ユーザー作成画面
  def new
    @departments = Department.sorted
    @employee_number = User.next_employee_number.to_s.rjust(4, '0')
    @user = User.new
  end

  # ユーザー作成処理
  def create
    @employee_number = User.next_employee_number.to_s.rjust(4, '0')
    @departments = Department.sorted

    @user = User.new(user_params.merge(
      employee_number:  User.next_employee_number,
      full_name: "#{user_params[:family_name]} #{user_params[:first_name]}",
      full_name_kana: "#{user_params[:family_name_kana]} #{user_params[:first_name_kana]}",
      password: Date.parse(user_params[:birthday]).strftime('%Y%m%d'),
      working_status: "not_working"
    ))

    if @user.save
      flash[:notice] = "新規ユーザーを登録しました。"
      redirect_to admin_users_path
    else
      Rails.logger.debug("User save failed: #{@user.errors.full_messages}")
      flash[:alert] = "ユーザー登録に失敗しました。"
      # 値を保持
      render :new
    end
  end

  # ユーザー削除
  def destroy

    user = User.find(params[:id])
    if user.destroy
      flash[:notice] = "#{user.full_name}さんを削除しました。"
      redirect_to admin_users_path
    else
      flash[:alert] = "#{user.full_name}さんの削除に失敗しました。"
      redirect_to admin_users_path
    end

  end

  # ユーザー編集
  def edit
    @departments = Department.sorted
    @employee_number = @user.employee_number.to_s.rjust(4, '0')

  end

  # ユーザー更新処理
  def update
    # 表示用
    @employee_number = User.next_employee_number
    @departments = Department.sorted

    if @user.update(user_params.merge(
      employee_number:  @user.employee_number,
      full_name: "#{user_params[:family_name]} #{user_params[:first_name]}",
      full_name_kana: "#{user_params[:family_name_kana]} #{user_params[:first_name_kana]}",
      password: Date.parse(user_params[:birthday]).strftime('%Y%m%d'),

      ))
      flash[:notice] = "#{@user.full_name}さんの情報を更新しました。"
      redirect_to admin_users_path
    else
      Rails.logger.debug("User update failed: #{@user.errors.full_messages}")
      flash[:alert] = "#{user.full_name}さんの情報の更新に失敗しました。"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :department_id, :family_name, :first_name, :family_name_kana, :first_name_kana,
      :birthday, :date_of_hire, :date_of_termination
    )
  end

  # フィルタリング条件に応じてユーザーを絞り込むメソッド
  def filter_users(users, filter)
    case filter
    when 'active'
      users.active # 在職中
    when 'retired'
      users.retired # 退職済
    else
      users # 全社員
    end
  end

  def department_filter_label(id)
    case id
    when ''
      'すべて'
    when 'none'
      '未設定'
    else
      department = Department.find_by(id: id)
      department.name
    end
  end

  def employee_filter_label(filter)
    case filter
      when 'active'
        '在職中'
      when 'retired'
        '退職済'
      else
        '全社員'
      end
  end

  def sort_column
    # 許可されていないカラムの場合employee_numberを返す
    %w[employee_number full_name_kana working_status date_of_hire date_of_termination ].include?(params[:sort_column]) ? params[:sort_column] : 'employee_number'
  end

  def sort_direction
    %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : 'asc'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, only:[:home] # ログイン中のユーザーを@userにセット
  before_action -> { set_and_verify_user(:id) }, only:[:show]

  # ホーム画面
  def home
    @works_today = @user.works.today.includes(:breaks).sorted
    @work = @works_today.latest_one.first
    @breaks =  @work&.breaks&.order(:start_datetime, :id)
  end

  # ユーザー詳細画面
  def show
  end

  private


end

app/helpers/users_helper.rb
module UsersHelper
  def working_status_icon(working_status)
    case working_status
    when "working"
      content_tag(:i, "", class: "bi bi-briefcase") # 勤務中のアイコン
    when "breaking"
      content_tag(:i, "", class: "bi bi-cup-hot") # 休憩中のアイコン
    when "not_working"
      content_tag(:i, "", class: "bi bi-house") # 勤務外のアイコン
    else
      content_tag(:i, "", class: "bi bi-question-circle") # 未登録のアイコン
    end
  end
end

app/views/admin/users/_user_form.html.haml
.headline 会社情報
%table.vertical-table
  %tbody
    %tr
      %th
        = f.label :employee_number, class: ' d-flex align-items-center' do
          %span 社員番号
          %span.badge.rounded-pill.text-bg-danger.mx-2 必須
      %td
        = f.text_field :employee_number, class: 'form-control', value: @employee_number, readonly: true, required: true, disabled: true
    %tr
      %th
        = f.label :department_id, class: 'form-label d-flex align-items-center' do
          %span 部署

      %td
        = f.collection_select :department_id, @departments, :id, :name, { prompt: "未選択" }, class: "form-select"
        .invalid-feedback
          部署を選択してください
    %tr
      %th
        = f.label :date_of_hire, class: 'form-label d-flex align-items-center' do
          %span 入社日
          %span.badge.rounded-pill.text-bg-danger.mx-2 必須
      %td
        = f.date_field :date_of_hire, class: 'form-control', required: true
        .invalid-feedback
          入力してください
    - if @user.persisted? # 編集の場合だけ退職日を表示
      %tr
        %th
          = f.label :date_of_termination, class: 'form-label d-flex align-items-center' do
            %span 退職日
        %td
          = f.date_field :date_of_termination, class: 'form-control'
          .form-text
            ※退職後はログインできなくなります
          .invalid-feedback
            入力してください



.headline 社員情報
%table.vertical-table
  %tbody
    %tr
      %th
        = f.label :family_name, class: 'form-label d-flex align-items-center' do
          %span 姓
          %span.badge.rounded-pill.text-bg-danger.mx-2 必須
      %td
        = f.text_field :family_name, class: 'form-control', required: true, pattern: "[ぁ-んァ-ン一-龥a-zA-Z]{1,20}"
        .invalid-feedback.text-wrap
          姓は20文字以内で、ひらがな、カタカナ、漢字、ローマ字を使用してください
    %tr
      %th
        = f.label :first_name, class: 'form-label d-flex align-items-center' do
          %span 名
          %span.badge.rounded-pill.text-bg-danger.mx-2 必須
      %td
        = f.text_field :first_name, class: 'form-control', required: true, pattern: "[ぁ-んァ-ン一-龥a-zA-Z]{1,20}"
        .invalid-feedback
          名は20文字以内で、ひらがな、カタカナ、漢字、ローマ字を使用してください
    %tr
      %th
        = f.label :family_name_kana, class: 'form-label d-flex align-items-center' do
          %span姓(かな)
      %td
        = f.text_field :family_name_kana, class: 'form-control', pattern: "[ぁ-ん]{1,30}"
        .invalid-feedback
          姓(かな)は30字以内で、ひらがなで入力してください。
    %tr
      %th
        = f.label :first_name_kana, class: 'form-label d-flex align-items-center' do
          %span 名(かな)
      %td
        = f.text_field :first_name_kana, class: 'form-control', pattern: "[ぁ-ん]{1,30}"
        .invalid-feedback
          名(かな)は30字以内で、ひらがなで入力してください。
    %tr
      %th
        = f.label :first_name, class: 'form-label d-flex align-items-center' do
          %span 生年月日
          %span.badge.rounded-pill.text-bg-danger.mx-2 必須
      %td
        = f.date_field :birthday, class: 'form-control', required: true
        .invalid-feedback
          生年月日を入力してください
.form-text.mb-3
  ※初回のログインパスワードは生年月日が設定されます。(例 2000年1月1日→20000101)

app/views/admin/users/_users_table.html.haml
%div.mb-2.d-flex.justify-content-between.align-items-center
  %div.d-flex.align-items-center
    %div.dropdown.me-3.align-items-center.d-flex
      %label 部署：
      %button.btn.btn-light.dropdown-toggle.text-dark.btn-sm{"data-bs-toggle" => "dropdown", "aria-expanded" => "false"}
        = @department_label
      %ul.dropdown-menu
        %li
          = link_to "すべて", admin_users_path(department_id: "", filter: params[:filter]), remote: true, class: "dropdown-item #{'selected' if @department_id == ''}"
        %li
          = link_to "未設定", admin_users_path(department_id: "none", filter: params[:filter]), remote: true, class: "dropdown-item #{'selected' if @department_id == 'none'}"
        - Department.pluck(:name, :id).each do |label, value|
          %li
            = link_to label, admin_users_path(department_id: value, filter: params[:filter]), remote: true, class: "dropdown-item #{'selected' if @department_id == value.to_s}"

    %div.dropdown.me-3.align-items-center.d-flex
      %label 社員：
      %button.btn.btn-light.dropdown-toggle.text-dark.btn-sm{"data-bs-toggle" => "dropdown", "aria-expanded" => "false"}
        = @employee_label
      %ul.dropdown-menu
        %li
          = link_to "在職中", admin_users_path(filter: "active", department_id: params[:department_id]), remote: true, class: "dropdown-item #{'selected' if @filter == 'active'}"
        %li
          = link_to "退職済", admin_users_path(filter: "retired", department_id: params[:department_id]), remote: true, class: "dropdown-item #{'selected' if @filter == 'retired'}"
        %li
          = link_to "全社員", admin_users_path(filter: "all", department_id: params[:department_id]), remote: true, class: "dropdown-item #{'selected' if @filter == ''}"
    = button_to 'リセット', admin_users_path, method: :get,  class: "btn btn-secondary btn-sm", remote: true
  = button_to '新規作成', new_admin_user_path, method: :get, class: "btn btn-primary"
.table-wrapper
  %table.table
    %thead
      %tr.align-middle
        %th
          = link_to admin_users_path(sort_column: "employee_number", sort_direction: @sort_column == 'employee_number' && @sort_direction == 'desc' ? 'asc' : 'desc', filter: params[:filter]), remote: true  do
            社員番号
            = sort_icon('employee_number')
        %th 部署
        %th
          = link_to  admin_users_path( sort_column: "full_name_kana", sort_direction: @sort_column == 'full_name_kana' && @sort_direction == 'desc' ? 'asc' : 'desc', filter: params[:filter]), remote: true  do
            名前
            = sort_icon('full_name_kana')
        %th
          = link_to  admin_users_path(sort_column: "working_status", sort_direction: @sort_column == 'working_status' && @sort_direction == 'desc' ? 'asc' : 'desc', filter: params[:filter]), remote: true  do
            ステータス
            = sort_icon('working_status')
        %th
          = link_to  admin_users_path( sort_column: "date_of_hire", sort_direction: @sort_column == 'date_of_hire' && @sort_direction == 'desc' ? 'asc' : 'desc', filter: params[:filter]), remote: true  do
            入社日
            = sort_icon('date_of_hire')
        %th
          = link_to  admin_users_path( sort_column: "date_of_termination", sort_direction: @sort_column == 'date_of_termination' && @sort_direction == 'desc' ? 'asc' : 'desc', filter: params[:filter]), remote: true  do
            退職日
            = sort_icon('date_of_termination')
        %th{ style: "width: 6rem;" }
        %th{ style: "width: 6rem;" }

    %tbody.table-group-divider
      - @users.each do |user|
        %tr.align-middle
          %td.text-dark= user.employee_number.to_s.rjust(4, '0') # 社員番号
          %td.text-dark= user.department&.name || "未設定" # 部署
          %td.text-dark= link_to truncate(user.full_name, length: 15), user_path(user.id) # 名前
          %td.text-dark= user.working_status_str # ステータス
          %td.text-dark= user.date_of_hire.strftime('%Y/%m/%d') # 入社日
          %td.text-dark= user.date_of_termination ? user.date_of_termination : "" # 退職日
          %td.text-dark= link_to '勤務履歴',  user_works_path(user.id), class: 'btn btn-primary btn-sm button-area' # 勤務履歴
          %td.text-dark= link_to '削除',  admin_user_path(user.id), method: :delete, data: {confirm: "#{user.full_name}さんを削除しますか？"}, class: 'btn btn-danger btn-sm button-area me-3' # 削除

app/views/admin/users/edit.html.haml
- breadcrumb :users_edit, @user, @admin_mode
- content_for(:title, '社員編集')

= form_with model: @user, url: @user.new_record? ? admin_users_path : admin_user_path(@user), local: true, html: { class: 'needs-validation', novalidate: true } do |f|
  = render "user_form", { f: f, user: @user }
  .d-flex.gap-2
    = link_to '戻る', user_path(@user), class: 'btn btn-secondary'
    = f.submit "更新", class: 'btn btn-primary'

app/views/admin/users/index.html.haml
- breadcrumb :users_index
- content_for(:title, '社員一覧')

#users-index-wrapper
  = render 'users_table'

app/views/admin/users/index.js.erb
document.getElementById("users-index-wrapper").innerHTML = `<%= j render 'users_table' %>`;

app/views/admin/users/new.html.haml
- breadcrumb :users_new
- content_for(:title, '社員登録')

= form_with model: @user, url: admin_users_path, local: true, html: { class: 'needs-validation', novalidate: true } do |f|
  = render "user_form", { f: f, user: @user }
  .d-flex.gap-2
    = link_to '戻る', admin_users_path, class: 'btn btn-secondary'
    = f.submit "登録", class: 'btn btn-primary'