config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # to (コントローラー名)(実行するアクション)


  # ログイン画面
  get 'login', to: 'sessions#new'          # ログインフォームを表示
  post 'login', to: 'sessions#create'      # ログイン処理
  delete 'logout', to: 'sessions#destroy'  # ログアウト処理


  resources :users, only: [:show] do
    collection do
      get 'home', to: 'users#home', as: 'home'
    end

    resources :companies, only: [:show]

    resources :works, only: [:index, :show, :create, :update] do
      get 'get_timeline_data', on: :member  # タイムラインデータを取得するルート
    end
    resources :breaks, only: [:index, :show, :create, :update]
  end

  # 管理者専用の操作
  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :companies, only: [:edit, :update]
  end

  post 'reset_demo_data', to: 'application#reset_demo_data'

  # 管理者モードの切り替え
  post 'toggle_admin_mode', to: 'admin#toggle_admin_mode'

  # ルートページをログイン画面に設定
  root 'sessions#new'
end

app/views/layouts/_footer.html.haml
%footer.footer
  %ul.md-flex
    %li
      %a{href: "https://rebel-calcium-078.notion.site/16a7aede4a9e8010a432e9f295fab50f?pvs=4", target: "_blank"} 設計書
    %li
      %a{href: "https://github.com/mkljla/kintai", target: "_blank"} GitHub
  %ul.md-flex
    %li
      = link_to 'デモデータをリセット',  'javascript:void(0);', id: 'reset-demo-data-button'
    #overlay{ style: 'display: none;' }
      .overlay-content
        %p デモデータをリセット中です。しばらくお待ちください
        .spinner-border{role: "status"}
          %span.visually-hidden Loading...

  %p.copyright © 2024 Ono. This application is a personal project developed for portfolio purposes.

app/views/layouts/_header.html.haml
%header.header-container{class: @admin_mode ? 'admin-mode' : ''}

  .wrapper.app-header__wrapper
    .app-header__start
      %a.brand{href: @admin_mode ? admin_users_path :  home_users_path} 勤怠管理アプリケーション

      - if current_user.is_admin
        .dropdown
          %button.btn.btn-primary.dropdown-toggle{type: "button", "data-bs-toggle" => "dropdown", "aria-expanded" => "false", class: @admin_mode ? 'btn-secondary' : 'btn-primary' }
            = @admin_mode ? "管理者モード" : "一般モード"
          %ul.dropdown-menu
            %li
              = link_to toggle_admin_mode_path, method: :post, class: 'dropdown-item' do
                = @admin_mode ? "一般モードに切り替える" : "管理者モードに切り替える"

    .app-header__end.text-primary-emphasis

      // ステータス
      %div.status_area.d-flex.badge.text-bg-light.rounded-pill
        %span.status_icon.me-1
          = working_status_icon(@current_user.working_status)
        %span.status_text
          = current_user.working_status_str

      .nav-item.dropdown
        %a.nav-link{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
          // 名前
          .d-flex
            .name_area.d-flex
              %span.name
                = truncate(current_user.full_name, length: 15)
              %span.san さん
            %i.bi.bi-chevron-down.mx-2

        // ドロップダウン中身
        %ul.dropdown-menu
          %li
            %a.dropdown-item{href:  user_path(current_user.id)}
              %i.bi.bi-person.me-1
              %span.menu-text 社員情報

          %hr.my-2
          %li
            = link_to logout_path, method: :delete, class: 'dropdown-item' do
              %i.bi.bi-box-arrow-right.me-1
              ログアウト

app/views/layouts/_sidebar.haml
%ul.nav.nav-pills.flex-column.mb-auto.sidebar-container

  %li
    %a.nav-link.link-body-emphasis{href:  home_users_path}
      %i.bi.bi-clock-history.mx-2.text-dark
      %span.menu-text.text-dark ホーム
  %li
    %a.nav-link.link-body-emphasis{href: user_works_path(current_user.id)}
      %i.bi.bi-file-ruled.mx-2.text-dark
      %span.menu-text.text-dark 勤務履歴
  %li
    %a.nav-link.link-body-emphasis{href: user_company_path(current_user.id, current_user.company_id)}
      %i.bi.bi-info-circle.mx-2.text-dark
      %span.menu-text.text-dark 会社情報

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}/
    = csrf_meta_tags
    = csp_meta_tag

    // Bootstrapの読み込み
    %link{crossorigin: "anonymous", href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", integrity: "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH", rel: "stylesheet"}/
    %script{src: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"}
    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css", rel: "stylesheet"}/
    // Google Charts
    = javascript_include_tag "https://www.gstatic.com/charts/loader.js"
    // カスタムCSSの読み込み
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    %title="勤怠管理アプリケーション"
  %body{
    "data-controller" => "#{controller.controller_path}", # ネームスペース込みのコントローラ名
    "data-action" => "#{controller.action_name}"
    }
    -if logged_in?
      .app-layout
        .app-header
          = render 'layouts/header'
        .main-layout
          .app-sidebar
            - if @admin_mode
              =render 'admin/layouts/sidebar'
            -else
              = render 'layouts/sidebar'
          .content-wrapper
            // パンくずリスト
            .breadcrumb-container
              = breadcrumbs separator: " &nbsp;&rsaquo;&nbsp; "
            .main-content
              = display_flash_messages
              // ページタイトル
              .page-title
                = yield(:title)
              //コンテンツ
              .content-body
                = yield
      .app-footer
        = render 'layouts/footer'
    - else
      .login-content
        = display_flash_messages
        = yield
        .app-footer
          = render 'layouts/footer'

    // JavaScript読み込み
    = javascript_include_tag 'application'